package com.moonsolstudios.kavvoro.ui.screens.language

import android.graphics.RectF
import com.moonsolstudios.kavvoro.i18n.KavvoroLanguage

/**
 * Geometric layout model for a single language card.
 */
data class LanguageCardLayout(
    val language: KavvoroLanguage,
    val bounds: RectF,
    val flagBounds: RectF,
    val textX: Float,
    val textCenterY: Float,
    val radioBounds: RectF
)

/**
 * Geometric layout model for the complete Language Selector screen.
 * Generated by [LanguageSelectorLayoutCalculator] as the single source of truth for rendering and touch hit testing.
 */
data class LanguageSelectorLayout(
    val scroll: Float,
    val maxScroll: Float,
    val panel: RectF,
    val header: RectF,
    val backButton: RectF,
    val backButtonHitbox: RectF,
    val gridViewport: RectF,
    val languageCards: List<LanguageCardLayout>,
    val footer: RectF,
    val columns: Int
) {
    val first: Float get() = scroll
    val second: Float get() = maxScroll
}
