package com.moonsolstudios.kavvoro.ui.render

import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Paint
import android.graphics.RectF
import android.graphics.Typeface
import com.moonsolstudios.kavvoro.engine.BallPower
import com.moonsolstudios.kavvoro.i18n.KavvoroLanguage
import com.moonsolstudios.kavvoro.model.BallSkin
import com.moonsolstudios.kavvoro.model.CollectionFilter
import com.moonsolstudios.kavvoro.model.LayoutMode
import com.moonsolstudios.kavvoro.model.MenuButton
import com.moonsolstudios.kavvoro.model.MenuState
import com.moonsolstudios.kavvoro.model.SettingsButton

object SubScreenMasterRenderer {

    fun drawMenu(
        canvas: Canvas,
        drawBackground: (Canvas) -> Unit,
        layoutMenuButtons: () -> Unit,
        menuState: MenuState,
        homeScale: Float,
        homeLayoutMode: LayoutMode,
        homeContentLeft: Float,
        homeContentWidth: Float,
        menuContentRight: Float,
        safeTopMenu: Float,
        selectedSkin: BallSkin,
        isRtl: Boolean,
        menuPrivacyButton: RectF,
        menuSfxButton: RectF,
        menuStartButton: RectF,
        menuLeaderboardButton: RectF,
        menuVaultButton: RectF,
        menuCollectionButton: RectF,
        menuStatsRects: List<RectF>,
        menuStatsTop: Float,
        menuStatsHeight: Float,
        activeMenuButton: MenuButton,
        sfxMuted: Boolean,
        bestStreak: Int,
        hypeBalance: Int,
        currentLevel: Int,
        dailyReady: Boolean,
        unlockedSkinCount: Int,
        totalSkinsCount: Int,
        nextRewardText: String?,
        centerX: Float,
        viewHeight: Float,
        safeInsetBottom: Float,
        paint: Paint,
        dp: Float,
        t: (String) -> String,
        fitText: (String, Float) -> String,
        formatHypeAmount: (Int) -> String,
        worldBitmap: (String) -> Bitmap?,
        drawPrimaryPlayButton: (Canvas, RectF) -> Unit,
        drawMenuPreview: (Canvas) -> Unit,
        drawPlayModeScreen: (Canvas, Float, Float, Float) -> Unit
    ) {
        drawBackground(canvas)
        layoutMenuButtons()

        HomeMenuRenderer.drawMenuScreen(
            canvas = canvas,
            menuState = menuState,
            homeScale = homeScale,
            homeLayoutMode = homeLayoutMode,
            homeContentLeft = homeContentLeft,
            homeContentWidth = homeContentWidth,
            menuContentRight = menuContentRight,
            safeTopMenu = safeTopMenu,
            selectedSkin = selectedSkin,
            isRtl = isRtl,
            menuPrivacyButton = menuPrivacyButton,
            menuSfxButton = menuSfxButton,
            menuStartButton = menuStartButton,
            menuLeaderboardButton = menuLeaderboardButton,
            menuVaultButton = menuVaultButton,
            menuCollectionButton = menuCollectionButton,
            menuStatsRects = menuStatsRects,
            menuStatsTop = menuStatsTop,
            menuStatsHeight = menuStatsHeight,
            activeMenuButton = activeMenuButton,
            sfxMuted = sfxMuted,
            bestStreak = bestStreak,
            hypeBalance = hypeBalance,
            currentLevel = currentLevel,
            dailyReady = dailyReady,
            unlockedSkinCount = unlockedSkinCount,
            totalSkinsCount = totalSkinsCount,
            nextRewardText = nextRewardText,
            centerX = centerX,
            viewHeight = viewHeight,
            safeInsetBottom = safeInsetBottom,
            paint = paint,
            dp = dp,
            t = t,
            fitText = fitText,
            formatHypeAmount = formatHypeAmount,
            worldBitmap = worldBitmap,
            drawPrimaryPlayButton = drawPrimaryPlayButton,
            drawMenuPreview = drawMenuPreview,
            drawPlayModeScreen = drawPlayModeScreen
        )
    }

    fun drawCollection(
        canvas: Canvas,
        layoutCollection: () -> Unit,
        collectionFilter: CollectionFilter,
        viewWidth: Float,
        viewHeight: Float,
        safeTop22: Float,
        safeTop54: Float,
        safeTop76: Float,
        safeTop104: Float,
        safeBottom70: Float,
        safeBottom16: Float,
        pageContentLeft: Float,
        pageContentRight: Float,
        collectionBackButton: RectF,
        collectionRestoreButton: RectF,
        collectionFilterRects: List<RectF>,
        collectionItemRects: List<RectF>,
        activeCollectionIndex: Int,
        collectionFilterActiveIndexFn: (Int) -> Int,
        collectionViewportTop: Float,
        collectionViewportBottom: Float,
        menuPulse: Float,
        ballSkins: List<BallSkin>,
        selectedSkin: BallSkin,
        focusedSkin: BallSkin,
        unlockedCount: Int,
        bestStreak: Int,
        hypeBalance: Int,
        formatHypeAmount: (Int) -> String,
        isSkinUnlocked: (BallSkin) -> Boolean,
        brainballBitmap: (BallSkin) -> Bitmap?,
        collectionMessage: String,
        nextRewardText: String?,
        paint: Paint,
        dp: Float,
        t: (String) -> String,
        fitText: (String, Float) -> String,
        drawFittedText: (Canvas, String, Float, Float, Float, Float, Float) -> Unit,
        drawWorldAsset: (Canvas, String, RectF, Int) -> Unit,
        drawUiButtonFrame: (Canvas, RectF, Boolean, Int, Float) -> Unit,
        drawUiIconAsset: (Canvas, String, RectF, Float, Int) -> Unit,
        powerIconKey: (BallPower) -> String,
        ballPowerName: (BallPower) -> String,
        ballPowerDescription: (BallPower) -> String,
        unlockShortLabel: (BallSkin) -> String,
        unlockLongLabel: (BallSkin) -> String,
        premiumPriceLabel: (BallSkin) -> String,
        premiumCompactPriceLabel: (BallSkin) -> String
    ) {
        layoutCollection()
        CollectionUiRenderer.drawCollectionScreen(
            canvas = canvas,
            viewWidth = viewWidth,
            viewHeight = viewHeight,
            safeTop22 = safeTop22,
            safeTop54 = safeTop54,
            safeTop76 = safeTop76,
            safeTop104 = safeTop104,
            safeBottom70 = safeBottom70,
            safeBottom16 = safeBottom16,
            pageContentLeft = pageContentLeft,
            pageContentRight = pageContentRight,
            collectionBackButton = collectionBackButton,
            collectionRestoreButton = collectionRestoreButton,
            collectionFilterRects = collectionFilterRects,
            collectionItemRects = collectionItemRects,
            collectionFilter = collectionFilter,
            activeCollectionIndex = activeCollectionIndex,
            collectionFilterActiveIndexFn = collectionFilterActiveIndexFn,
            collectionViewportTop = collectionViewportTop,
            collectionViewportBottom = collectionViewportBottom,
            menuPulse = menuPulse,
            ballSkins = ballSkins,
            selectedSkin = selectedSkin,
            focusedSkin = focusedSkin,
            unlockedCount = unlockedCount,
            bestStreak = bestStreak,
            hypeBalance = hypeBalance,
            formatHypeAmount = formatHypeAmount,
            isSkinUnlocked = isSkinUnlocked,
            brainballBitmap = brainballBitmap,
            collectionMessage = collectionMessage,
            nextRewardText = nextRewardText,
            paint = paint,
            dp = dp,
            t = t,
            fitText = fitText,
            drawFittedText = drawFittedText,
            drawWorldAsset = drawWorldAsset,
            drawUiButtonFrame = drawUiButtonFrame,
            drawUiIconAsset = drawUiIconAsset,
            powerIconKey = powerIconKey,
            ballPowerName = ballPowerName,
            ballPowerDescription = ballPowerDescription,
            unlockShortLabel = unlockShortLabel,
            unlockLongLabel = unlockLongLabel,
            premiumPriceLabel = premiumPriceLabel,
            premiumCompactPriceLabel = premiumCompactPriceLabel
        )
    }

    fun drawLeaderboards(
        canvas: Canvas,
        drawBackground: (Canvas) -> Unit,
        layoutLeaderboards: () -> Unit,
        scores: List<String>,
        pageLeft: Float,
        pageRight: Float,
        pageWidth: Float,
        viewWidth: Float,
        top56: Float,
        top78: Float,
        bandTop: Float,
        bandBottom: Float,
        top118: Float,
        top146: Float,
        bottom70: Float,
        bottom16: Float,
        configured: Boolean,
        highestLevelText: String,
        bestStreakText: String,
        activeLeaderboardIndex: Int,
        leaderboardBackButton: RectF,
        leaderboardItemRects: List<RectF>,
        leaderboardMessage: String,
        paint: Paint,
        dp: Float,
        t: (String) -> String,
        fitText: (String, Float) -> String,
        drawBackButton: (Canvas, RectF, Boolean) -> Unit
    ) {
        drawBackground(canvas)
        layoutLeaderboards()

        LeaderboardUiRenderer.drawScreen(
            canvas = canvas,
            pageLeft = pageLeft,
            pageRight = pageRight,
            pageWidth = pageWidth,
            viewWidth = viewWidth,
            top56 = top56,
            top78 = top78,
            bandTop = bandTop,
            bandBottom = bandBottom,
            top118 = top118,
            top146 = top146,
            bottom70 = bottom70,
            bottom16 = bottom16,
            configured = configured,
            highestLevelText = highestLevelText,
            bestStreakText = bestStreakText,
            leaderboardScores = scores,
            activeLeaderboardIndex = activeLeaderboardIndex,
            leaderboardBackButton = leaderboardBackButton,
            leaderboardItemRects = leaderboardItemRects,
            leaderboardMessage = leaderboardMessage,
            paint = paint,
            dp = dp,
            t = t,
            fitText = fitText,
            drawBackButton = drawBackButton
        )
    }

    fun drawSettings(
        canvas: Canvas,
        layoutSettings: () -> Unit,
        viewWidth: Float,
        viewHeight: Float,
        safeTop24: Float,
        safeTop112: Float,
        safeTop132: Float,
        safeCenterX: Float,
        pageContentLeft: Float,
        pageContentRight: Float,
        settingsViewportTop: Float,
        settingsViewportBottom: Float,
        compact: Boolean,
        settingsHeaderGearButton: RectF,
        activeSettingsButton: SettingsButton,
        settingsMasterButton: RectF,
        settingsMasterSlider: RectF,
        settingsMasterVolume: Int,
        settingsMusicButton: RectF,
        settingsMusicSlider: RectF,
        settingsMusicVolume: Int,
        settingsSfxButton: RectF,
        settingsSfxSlider: RectF,
        settingsSfxVolume: Int,
        settingsHapticToggle: RectF,
        settingsHapticEnabled: Boolean,
        settingsShakeToggle: RectF,
        settingsScreenShake: Boolean,
        settingsPerformanceToggle: RectF,
        settingsPerformanceMode: Boolean,
        settingsLanguageButton: RectF,
        selectedLanguageLabel: String,
        settingsAccountButton: RectF,
        settingsPrivacyButton: RectF,
        settingsTermsButton: RectF,
        settingsAboutButton: RectF,
        versionName: String,
        settingsResetButton: RectF,
        settingsBackButton: RectF,
        settingsResetConfirm: Boolean,
        settingsResetCancelButton: RectF,
        settingsResetConfirmButton: RectF,
        paint: Paint,
        dp: Float,
        fitText: (String, Float) -> String,
        drawBrandTitle: (Canvas, Float, Float) -> Unit,
        drawUiButtonFrame: (Canvas, RectF, Boolean, Int, Float) -> Unit,
        drawAudioIconAsset: (Canvas, RectF, String, Boolean, Boolean) -> Unit
    ) {
        layoutSettings()
        SettingsUiRenderer.drawSettingsScreen(
            canvas = canvas,
            viewWidth = viewWidth,
            viewHeight = viewHeight,
            safeTop24 = safeTop24,
            safeTop112 = safeTop112,
            safeTop132 = safeTop132,
            safeCenterX = safeCenterX,
            pageContentLeft = pageContentLeft,
            pageContentRight = pageContentRight,
            settingsViewportTop = settingsViewportTop,
            settingsViewportBottom = settingsViewportBottom,
            compact = compact,
            settingsHeaderGearButton = settingsHeaderGearButton,
            activeSettingsButton = activeSettingsButton,
            settingsMasterButton = settingsMasterButton,
            settingsMasterSlider = settingsMasterSlider,
            settingsMasterVolume = settingsMasterVolume,
            settingsMusicButton = settingsMusicButton,
            settingsMusicSlider = settingsMusicSlider,
            settingsMusicVolume = settingsMusicVolume,
            settingsSfxButton = settingsSfxButton,
            settingsSfxSlider = settingsSfxSlider,
            settingsSfxVolume = settingsSfxVolume,
            settingsHapticToggle = settingsHapticToggle,
            settingsHapticEnabled = settingsHapticEnabled,
            settingsShakeToggle = settingsShakeToggle,
            settingsScreenShake = settingsScreenShake,
            settingsPerformanceToggle = settingsPerformanceToggle,
            settingsPerformanceMode = settingsPerformanceMode,
            settingsLanguageButton = settingsLanguageButton,
            selectedLanguageLabel = selectedLanguageLabel,
            settingsAccountButton = settingsAccountButton,
            settingsPrivacyButton = settingsPrivacyButton,
            settingsTermsButton = settingsTermsButton,
            settingsAboutButton = settingsAboutButton,
            versionName = versionName,
            settingsResetButton = settingsResetButton,
            settingsBackButton = settingsBackButton,
            settingsResetConfirm = settingsResetConfirm,
            settingsResetCancelButton = settingsResetCancelButton,
            settingsResetConfirmButton = settingsResetConfirmButton,
            paint = paint,
            dp = dp,
            fitText = fitText,
            drawBrandTitle = drawBrandTitle,
            drawUiButtonFrame = drawUiButtonFrame,
            drawAudioIconAsset = drawAudioIconAsset
        )
    }

    fun drawLanguage(
        canvas: Canvas,
        layoutSelector: () -> Unit,
        side: Float,
        contentRight: Float,
        contentWidth: Float,
        compact: Boolean,
        centerX: Float,
        selected: KavvoroLanguage,
        activeLanguageIndex: Int,
        headerFrameBmp: Bitmap?,
        diamondBmp: Bitmap?,
        backButtonRect: RectF,
        backButtonBmp: Bitmap?,
        itemRects: List<RectF>,
        viewportTop: Float,
        viewportBottom: Float,
        footerRect: RectF,
        footerBmp: Bitmap?,
        langCardBitmap: (Boolean, Boolean) -> Bitmap?,
        languageFlagBitmap: (KavvoroLanguage) -> Bitmap?,
        langRadioBitmap: (Boolean) -> Bitmap?,
        typeface: Typeface?,
        paint: Paint,
        dp: Float,
        t: (String) -> String,
        fitText: (String, Float) -> String,
        drawFlagFallback: (Canvas, RectF, KavvoroLanguage) -> Unit
    ) {
        layoutSelector()
        LanguageSelectorRenderer.drawScreen(
            canvas = canvas,
            side = side,
            contentRight = contentRight,
            contentWidth = contentWidth,
            compact = compact,
            centerX = centerX,
            selected = selected,
            activeLanguageIndex = activeLanguageIndex,
            headerFrameBmp = headerFrameBmp,
            diamondBmp = diamondBmp,
            backButtonRect = backButtonRect,
            backButtonBmp = backButtonBmp,
            itemRects = itemRects,
            viewportTop = viewportTop,
            viewportBottom = viewportBottom,
            footerRect = footerRect,
            footerBmp = footerBmp,
            langCardBitmap = langCardBitmap,
            languageFlagBitmap = languageFlagBitmap,
            langRadioBitmap = langRadioBitmap,
            typeface = typeface,
            paint = paint,
            dp = dp,
            t = t,
            fitText = fitText,
            drawFlagFallback = drawFlagFallback
        )
    }
}
