package com.moonsolstudios.kavvoro.repository

import com.moonsolstudios.kavvoro.R
import com.moonsolstudios.kavvoro.engine.BallPower
import com.moonsolstudios.kavvoro.model.BallSkin
import com.moonsolstudios.kavvoro.model.SkinStyle
import com.moonsolstudios.kavvoro.model.UnlockRule
import com.moonsolstudios.kavvoro.model.UnlockType

/**
 * Single source of truth for all 50 Brainball skins and their drawable asset mappings.
 */
object BallSkinCatalog {

    val ALL_SKINS: List<BallSkin> = listOf(
BallSkin("prism_king", "VORO PRIME", "unlimited aura final boss", 0xFFF7F4FF.toInt(), 0xFF8AA6FF.toInt(), 0xFFFFCF4A.toInt(), SkinStyle.PRISM, UnlockRule(UnlockType.PREMIUM, 0, "Premium 0.99 local price"), BallPower.PRISM_SHIELD),
        BallSkin("void_zero", "KAV ZERO", "taxed the void at 3am", 0xFF07090F.toInt(), 0xFFFF4D8D.toInt(), 0xFF45F2FF.toInt(), SkinStyle.VOID, UnlockRule(UnlockType.PREMIUM, 0, "Premium 0.99 local price"), BallPower.VOID_PHASE),
        BallSkin("chrome_lux", "CHROME VORO", "sigma mirror from ohio", 0xFFE6EDF7.toInt(), 0xFF1DE8C8.toInt(), 0xFFFF4D8D.toInt(), SkinStyle.CHROME, UnlockRule(UnlockType.PREMIUM, 0, "Premium 0.99 local price"), BallPower.CHROME_RICOCHET),
        BallSkin("plasma_crown", "NOVA KAV", "galaxy rizz meltdown", 0xFFFFCF4A.toInt(), 0xFFC15CFF.toInt(), 0xFFFF8C42.toInt(), SkinStyle.PLASMA, UnlockRule(UnlockType.PREMIUM, 0, "Premium 0.99 local price"), BallPower.PLASMA_SURGE),
        BallSkin("nodlo", "KAVVORO", "the original brainrot specimen", 0xFFF7F4FF.toInt(), 0xFF1DE8C8.toInt(), 0xFF1DE8C8.toInt(), SkinStyle.CLASSIC, UnlockRule(UnlockType.DEFAULT, 0, "Unlocked")),
        BallSkin("curse_grad", "VORO GRAD", "graduated brain academy", 0xFF8AA6FF.toInt(), 0xFFFFCF4A.toInt(), 0xFF8AA6FF.toInt(), SkinStyle.CROWN, UnlockRule(UnlockType.TUTORIAL_CLEAR, 10, "Clear tutorial L10")),
        BallSkin("blop_13", "BLOP VORO", "emotionally aerodynamic", 0xFF64E572.toInt(), 0xFF07090F.toInt(), 0xFF64E572.toInt(), SkinStyle.BLOP, UnlockRule(UnlockType.CLASSIC_LEVEL, 25, "Clear Classic L25")),
        BallSkin("fizz_nana", "FIZZ KAV", "battery ate the charger", 0xFFFFCF4A.toInt(), 0xFF07090F.toInt(), 0xFFFFCF4A.toInt(), SkinStyle.ZAP, UnlockRule(UnlockType.BEST_STREAK, 15, "Reach streak 15")),
        BallSkin("lala_glitch", "LALA VORO", "wifi password was wrong", 0xFFFF4D8D.toInt(), 0xFF45F2FF.toInt(), 0xFFFF4D8D.toInt(), SkinStyle.GLITCH, UnlockRule(UnlockType.CHAOS_LEVEL, 25, "Clear Chaos L25")),
        BallSkin("womp_loop", "WOMP KAV", "looping the same thought", 0xFF8AA6FF.toInt(), 0xFFFFCF4A.toInt(), 0xFF8AA6FF.toInt(), SkinStyle.LOOP, UnlockRule(UnlockType.BEST_STREAK, 25, "Reach streak 25")),
        BallSkin("mimi_static", "MIMI VORO", "staring aggressively in 4k", 0xFFC15CFF.toInt(), 0xFFF7F4FF.toInt(), 0xFFC15CFF.toInt(), SkinStyle.STATIC, UnlockRule(UnlockType.CLASSIC_LEVEL, 40, "Clear Classic L40")),
        BallSkin("zaza_volt", "ZAZA KAV", "too fast for homework", 0xFFFF8C42.toInt(), 0xFF07090F.toInt(), 0xFFFF8C42.toInt(), SkinStyle.ZAP, UnlockRule(UnlockType.BEST_STREAK, 35, "Reach streak 35")),
        BallSkin("tik_rift", "TIKKAV RIFT", "the wind owes him money", 0xFF45F2FF.toInt(), 0xFF431934.toInt(), 0xFF45F2FF.toInt(), SkinStyle.RIFT, UnlockRule(UnlockType.CLASSIC_LEVEL, 55, "Clear Classic L55")),
        BallSkin("byte_baba", "BYTE VORO", "born in the share button", 0xFFF7F4FF.toInt(), 0xFFFF4D8D.toInt(), 0xFFF7F4FF.toInt(), SkinStyle.BYTE, UnlockRule(UnlockType.SHARE_COUNT, 5, "Share five replays")),
        BallSkin("globo_wobble", "GLOBO KAV", "gravity's unemployed cousin", 0xFF1DE8C8.toInt(), 0xFFFFCF4A.toInt(), 0xFF1DE8C8.toInt(), SkinStyle.WOBBLE, UnlockRule(UnlockType.CHAOS_LEVEL, 30, "Clear Chaos L30")),
        BallSkin("rift_baba", "ELDER VORO", "ancient forbidden yapping", 0xFF431934.toInt(), 0xFFFFCF4A.toInt(), 0xFFFF4D8D.toInt(), SkinStyle.RIFT, UnlockRule(UnlockType.CHAOS_LEVEL, 50, "Clear Chaos L50")),
        BallSkin("king_static", "KING KAV", "maximum aura no evidence", 0xFFFFCF4A.toInt(), 0xFFFF4D8D.toInt(), 0xFFFFCF4A.toInt(), SkinStyle.CROWN, UnlockRule(UnlockType.BEST_STREAK, 25, "Reach streak 25")),
        BallSkin("nibbi_kav", "NIBBI KAV", "forgot why it entered", 0xFF7EE787.toInt(), 0xFF1F2937.toInt(), 0xFF7EE787.toInt(), SkinStyle.BLOP, UnlockRule(UnlockType.CLASSIC_LEVEL, 35, "Clear Classic L35")),
        BallSkin("voro_rizz", "VORO RIZZ", "unlicensed aura dealer", 0xFFFF7AB2.toInt(), 0xFF231942.toInt(), 0xFFFF7AB2.toInt(), SkinStyle.LOOP, UnlockRule(UnlockType.CHAOS_LEVEL, 40, "Clear Chaos L40")),
        BallSkin("bongo_kav", "BONGO KAV", "thinks in drum noises", 0xFFFFA94D.toInt(), 0xFF101820.toInt(), 0xFFFFA94D.toInt(), SkinStyle.WOBBLE, UnlockRule(UnlockType.HYPE_COST, 7_500, "Unlock with 7500 HYPE")),
        BallSkin("glitch_nona", "GLITCH NONA", "buffering since birth", 0xFFB765FF.toInt(), 0xFF45F2FF.toInt(), 0xFFB765FF.toInt(), SkinStyle.GLITCH, UnlockRule(UnlockType.CLASSIC_LEVEL, 50, "Clear Classic L50")),
        BallSkin("sloppi_voro", "SLOPPI VORO", "microwaved premium water", 0xFF65E6A7.toInt(), 0xFF342A21.toInt(), 0xFF65E6A7.toInt(), SkinStyle.BLOP, UnlockRule(UnlockType.HYPE_COST, 14_000, "Unlock with 14000 HYPE")),
        BallSkin("kav_kaboom", "KAV KABOOM", "volume permanently maximum", 0xFFFF5757.toInt(), 0xFFFFCF4A.toInt(), 0xFFFF5757.toInt(), SkinStyle.ZAP, UnlockRule(UnlockType.SHARE_COUNT, 10, "Share ten replays")),
        BallSkin("drippi_mim", "DRIPPI MIM", "wearing invisible sneakers", 0xFF45F2FF.toInt(), 0xFFFF4D8D.toInt(), 0xFF45F2FF.toInt(), SkinStyle.CHROME, UnlockRule(UnlockType.HYPE_COST, 22_000, "Unlock with 22000 HYPE")),
        BallSkin("nappa_voro", "NAPPA VORO", "sleeping at full speed", 0xFF8AA6FF.toInt(), 0xFF2B2440.toInt(), 0xFF8AA6FF.toInt(), SkinStyle.STATIC, UnlockRule(UnlockType.CLASSIC_LEVEL, 75, "Clear Classic L75")),
        BallSkin("yappa_kav", "YAPPA KAV", "podcast with no microphone", 0xFFFF8C42.toInt(), 0xFFC15CFF.toInt(), 0xFFFF8C42.toInt(), SkinStyle.LOOP, UnlockRule(UnlockType.CHAOS_LEVEL, 75, "Clear Chaos L75")),
        BallSkin("turbo_blob", "TURBO BLOB", "zero brakes many opinions", 0xFF64E572.toInt(), 0xFFFFCF4A.toInt(), 0xFF64E572.toInt(), SkinStyle.WOBBLE, UnlockRule(UnlockType.BEST_STREAK, 50, "Reach streak 50")),
        BallSkin("wifi_voro", "WIFI VORO", "connected without internet", 0xFF45F2FF.toInt(), 0xFF07090F.toInt(), 0xFF45F2FF.toInt(), SkinStyle.RIFT, UnlockRule(UnlockType.CLASSIC_LEVEL, 100, "Clear Classic L100")),
        BallSkin("cringe_kav", "CRINGE KAV", "weaponized secondhand shame", 0xFFFF4D8D.toInt(), 0xFFFFCF4A.toInt(), 0xFFFF4D8D.toInt(), SkinStyle.GLITCH, UnlockRule(UnlockType.CHAOS_LEVEL, 100, "Clear Chaos L100")),
        BallSkin("kav_404", "KAV 404", "thought process not found", 0xFFF7F4FF.toInt(), 0xFFFF5757.toInt(), 0xFFF7F4FF.toInt(), SkinStyle.BYTE, UnlockRule(UnlockType.SHARE_COUNT, 20, "Share twenty replays")),
        BallSkin("pasta_voro", "PASTA VORO", "certified sauce technician", 0xFFFFCF4A.toInt(), 0xFFFF4D8D.toInt(), 0xFFFFCF4A.toInt(), SkinStyle.LOOP, UnlockRule(UnlockType.HYPE_COST, 34_000, "Unlock with 34000 HYPE")),
        BallSkin("laggi_kav", "LAGGI KAV", "arrived three frames late", 0xFFC15CFF.toInt(), 0xFF45F2FF.toInt(), 0xFFC15CFF.toInt(), SkinStyle.STATIC, UnlockRule(UnlockType.CLASSIC_LEVEL, 125, "Clear Classic L125")),
        BallSkin("moggo_voro", "MOGGO VORO", "jawline rendered separately", 0xFF1DE8C8.toInt(), 0xFF431934.toInt(), 0xFF1DE8C8.toInt(), SkinStyle.PRISM, UnlockRule(UnlockType.CHAOS_LEVEL, 125, "Clear Chaos L125")),
        BallSkin("brain_bean", "BRAIN BEAN", "one bean two braincells", 0xFF64E572.toInt(), 0xFFC15CFF.toInt(), 0xFF64E572.toInt(), SkinStyle.BLOP, UnlockRule(UnlockType.HYPE_COST, 55_000, "Unlock with 55000 HYPE"), BallPower.MINOR_RICOCHET),
        BallSkin("aura_thief", "AURA THIEF", "borrowed everything forever", 0xFF07090F.toInt(), 0xFFFFCF4A.toInt(), 0xFFFFCF4A.toInt(), SkinStyle.VOID, UnlockRule(UnlockType.CLASSIC_LEVEL, 150, "Clear Classic L150")),
        BallSkin("gigi_glitch", "GIGI GLITCH", "reality needs an update", 0xFFFF4D8D.toInt(), 0xFF45F2FF.toInt(), 0xFFFF4D8D.toInt(), SkinStyle.GLITCH, UnlockRule(UnlockType.CHAOS_LEVEL, 150, "Clear Chaos L150")),
        BallSkin("noodle_kav", "NOODLE KAV", "structurally just vibes", 0xFFFFCF4A.toInt(), 0xFF64E572.toInt(), 0xFFFFCF4A.toInt(), SkinStyle.WOBBLE, UnlockRule(UnlockType.SHARE_COUNT, 30, "Share thirty replays")),
        BallSkin("sleepy_voro", "SLEEPY VORO", "dreaming in leaderboard points", 0xFF8AA6FF.toInt(), 0xFF07090F.toInt(), 0xFF8AA6FF.toInt(), SkinStyle.STATIC, UnlockRule(UnlockType.HYPE_COST, 85_000, "Unlock with 85000 HYPE"), BallPower.MINOR_PHASE),
        BallSkin("panic_bean", "PANIC BEAN", "calm mode sold separately", 0xFFFF8C42.toInt(), 0xFFFF4D8D.toInt(), 0xFFFF8C42.toInt(), SkinStyle.ZAP, UnlockRule(UnlockType.CLASSIC_LEVEL, 200, "Clear Classic L200")),
        BallSkin("bossy_blop", "BOSSY BLOP", "promoted itself during lunch", 0xFF64E572.toInt(), 0xFFFFCF4A.toInt(), 0xFF64E572.toInt(), SkinStyle.CROWN, UnlockRule(UnlockType.CHAOS_LEVEL, 200, "Clear Chaos L200")),
        BallSkin("quantum_kav", "QUANTUM KAV", "winning and crashing together", 0xFF45F2FF.toInt(), 0xFFC15CFF.toInt(), 0xFF45F2FF.toInt(), SkinStyle.PRISM, UnlockRule(UnlockType.HYPE_COST, 130_000, "Unlock with 130000 HYPE"), BallPower.MINOR_SURGE),
        BallSkin("wobble_ceo", "WOBBLE CEO", "owns three fake companies", 0xFFFFCF4A.toInt(), 0xFF1DE8C8.toInt(), 0xFFFFCF4A.toInt(), SkinStyle.WOBBLE, UnlockRule(UnlockType.CLASSIC_LEVEL, 250, "Clear Classic L250")),
        BallSkin("error_voro", "ERROR VORO", "too forbidden to compile", 0xFFFF5757.toInt(), 0xFF07090F.toInt(), 0xFFFF5757.toInt(), SkinStyle.BYTE, UnlockRule(UnlockType.CHAOS_LEVEL, 250, "Clear Chaos L250")),
        BallSkin("golden_yap", "GOLDEN YAP", "talking in legendary subtitles", 0xFFFFCF4A.toInt(), 0xFFF7F4FF.toInt(), 0xFFFFCF4A.toInt(), SkinStyle.CROWN, UnlockRule(UnlockType.SHARE_COUNT, 50, "Share fifty replays")),
        BallSkin("void_junior", "VOID JUNIOR", "small void huge confidence", 0xFF18111F.toInt(), 0xFFFF4D8D.toInt(), 0xFFC15CFF.toInt(), SkinStyle.VOID, UnlockRule(UnlockType.BEST_STREAK, 150, "Reach streak 150")),
        BallSkin("kav_maxx", "KAV MAXX", "every slider set to illegal", 0xFFF7F4FF.toInt(), 0xFFFF5757.toInt(), 0xFFFFCF4A.toInt(), SkinStyle.PLASMA, UnlockRule(UnlockType.CLASSIC_LEVEL, 300, "Clear Classic L300")),
        BallSkin("rift_rizzler", "RIFT RIZZLER", "gravity follows his account", 0xFF431934.toInt(), 0xFF45F2FF.toInt(), 0xFFFF4D8D.toInt(), SkinStyle.RIFT, UnlockRule(UnlockType.CHAOS_LEVEL, 300, "Clear Chaos L300")),
        BallSkin("ultra_nona", "ULTRA NONA", "recharges from pure yapping", 0xFFC15CFF.toInt(), 0xFFFFCF4A.toInt(), 0xFFC15CFF.toInt(), SkinStyle.PLASMA, UnlockRule(UnlockType.BEST_STREAK, 200, "Reach streak 200"), BallPower.MINOR_SURGE),
        BallSkin("aura_titan", "AURA TITAN", "phases through awkward moments", 0xFFF7F4FF.toInt(), 0xFF8AA6FF.toInt(), 0xFF45F2FF.toInt(), SkinStyle.PRISM, UnlockRule(UnlockType.CLASSIC_LEVEL, 400, "Clear Classic L400"), BallPower.MINOR_PHASE),
        BallSkin("final_voro", "FINAL VORO", "bounces beyond the lore", 0xFFFFCF4A.toInt(), 0xFFFF4D8D.toInt(), 0xFFF7F4FF.toInt(), SkinStyle.CROWN, UnlockRule(UnlockType.CHAOS_LEVEL, 400, "Clear Chaos L400"), BallPower.MINOR_RICOCHET)
    )

    val ART_RESOURCES: Map<String, Int> = mapOf(
        "prism_king" to R.drawable.brainball_prism_king,
        "void_zero" to R.drawable.brainball_void_zero,
        "chrome_lux" to R.drawable.brainball_chrome_lux,
        "plasma_crown" to R.drawable.brainball_plasma_crown,
        "nodlo" to R.drawable.brainball_nodlo,
        "curse_grad" to R.drawable.brainball_curse_grad,
        "blop_13" to R.drawable.brainball_blop_13,
        "fizz_nana" to R.drawable.brainball_fizz_nana,
        "lala_glitch" to R.drawable.brainball_lala_glitch,
        "womp_loop" to R.drawable.brainball_womp_loop,
        "mimi_static" to R.drawable.brainball_mimi_static,
        "zaza_volt" to R.drawable.brainball_zaza_volt,
        "tik_rift" to R.drawable.brainball_tik_rift,
        "byte_baba" to R.drawable.brainball_byte_baba,
        "globo_wobble" to R.drawable.brainball_globo_wobble,
        "rift_baba" to R.drawable.brainball_rift_baba,
        "king_static" to R.drawable.brainball_king_static,
        "nibbi_kav" to R.drawable.brainball_nibbi_kav,
        "voro_rizz" to R.drawable.brainball_voro_rizz,
        "bongo_kav" to R.drawable.brainball_bongo_kav,
        "glitch_nona" to R.drawable.brainball_glitch_nona,
        "sloppi_voro" to R.drawable.brainball_sloppi_voro,
        "kav_kaboom" to R.drawable.brainball_kav_kaboom,
        "drippi_mim" to R.drawable.brainball_drippi_mim,
        "nappa_voro" to R.drawable.brainball_nappa_voro,
        "yappa_kav" to R.drawable.brainball_yappa_kav,
        "turbo_blob" to R.drawable.brainball_turbo_blob,
        "wifi_voro" to R.drawable.brainball_wifi_voro,
        "cringe_kav" to R.drawable.brainball_cringe_kav,
        "kav_404" to R.drawable.brainball_kav_404,
        "pasta_voro" to R.drawable.brainball_pasta_voro,
        "laggi_kav" to R.drawable.brainball_laggi_kav,
        "moggo_voro" to R.drawable.brainball_moggo_voro,
        "brain_bean" to R.drawable.brainball_brain_bean,
        "aura_thief" to R.drawable.brainball_aura_thief,
        "gigi_glitch" to R.drawable.brainball_gigi_glitch,
        "noodle_kav" to R.drawable.brainball_noodle_kav,
        "sleepy_voro" to R.drawable.brainball_sleepy_voro,
        "panic_bean" to R.drawable.brainball_panic_bean,
        "bossy_blop" to R.drawable.brainball_bossy_blop,
        "quantum_kav" to R.drawable.brainball_quantum_kav,
        "wobble_ceo" to R.drawable.brainball_wobble_ceo,
        "error_voro" to R.drawable.brainball_error_voro,
        "golden_yap" to R.drawable.brainball_golden_yap,
        "void_junior" to R.drawable.brainball_void_junior,
        "kav_maxx" to R.drawable.brainball_kav_maxx,
        "rift_rizzler" to R.drawable.brainball_rift_rizzler,
        "ultra_nona" to R.drawable.brainball_ultra_nona,
        "aura_titan" to R.drawable.brainball_aura_titan,
        "final_voro" to R.drawable.brainball_final_voro
    )
}
